# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - main

resources:
  - repo: self

variables:
  buildId: '$(Build.BuildId)'

stages:
  - stage: SonarCloud_Scanning
    displayName: SonarCloud_Scanning
    jobs:
      - job: Fetch
        displayName: Fetch
        steps:
          - checkout: self
            fetchDepth: 0
          - task: SonarCloudPrepare@1
            inputs:
              SonarCloud: 'sonarcloud-app-core'
              organization: 'axacde'
              scannerMode: 'Other'
              extraProperties: |
                # Additional properties that will be passed to the scanner, 
                # Put one key=value per line, example:
                # sonar.exclusions=**/*.bin
                sonar.projectKey=axacde_app-core
                sonar.projectName=app-core
          - task: SonarCloudAnalyze@1
          - task: SonarCloudPublish@1
            inputs:
              pollingTimeoutSec: '300'
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build
        pool:
          name: PrivateAgent
        steps:
          - task: Bash@3
            displayName: Pipeline Preparation [env, m2, PATH]
            inputs:
              targetType: 'inline'
              script: 'echo "##vso[task.setvariable variable=M2_HOME]/opt/apache-maven-3.6.3" && export PATH=PATH:/opt/apache-maven-3.6.3'

          - task: Maven@3
            displayName: Publish packages to Azure Artifacts Feed
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'deploy'
              publishJUnitResults: false
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              jdkUserInputPath: '/opt/jdk-13.0.1'
              mavenDirectory: '/opt/apache-maven-3.6.3'
              mavenSetM2Home: '/opt/apache-maven-3.6.3'
              javaHomeOption: '/opt/jdk-13.0.1' # 'JDKVersion' | 'Path'. Alias: javaHomeSelection. Required. Set JAVA_HOME by. Default: JDKVersion.
              mavenVersionOption: 'Default' # 'Default' | 'Path'. Alias: mavenVersionSelection. Required. Maven version. Default: Default.
              mavenAuthenticateFeed: false # boolean. Alias: mavenFeedAuthenticate. Required. Authenticate built-in Maven feeds. Default: false.
              effectivePomSkip: false # boolean. Alias: skipEffectivePom. Required. Skip generating effective POM while authenticating built-in feeds. Default: false.
              # Code Analysis
              sonarQubeRunAnalysis: false # boolean. Alias: sqAnalysisEnabled. Required. Run SonarQube or SonarCloud analysis. Default: false.
